// Reads extension/.env (falls back to .env.example) and writes src/config.js
// so API_BASE_URL is a build-time value, never hardcoded in source files
// that ship to the browser.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const envPath = existsSync(join(root, ".env")) ? join(root, ".env") : join(root, ".env.example");

const env = Object.fromEntries(
  readFileSync(envPath, "utf-8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"))
    .map((line) => {
      const idx = line.indexOf("=");
      return [line.slice(0, idx), line.slice(idx + 1)];
    })
);

const apiBaseUrl = env.API_BASE_URL || "http://localhost:8000";

writeFileSync(
  join(root, "src", "config.js"),
  `// Generated by scripts/generate-config.js from .env — do not edit by hand.\nexport const API_BASE_URL = ${JSON.stringify(apiBaseUrl)};\n`
);

console.log(`extension/src/config.js written with API_BASE_URL=${apiBaseUrl}`);
