"""initial schema (matches existing Neon tables)

Revision ID: bb3349e05c3f
Revises: 
Create Date: 2026-07-04 00:31:36.560573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb3349e05c3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_auth_logs_card_id', table_name='auth_logs')
    op.drop_index('idx_auth_logs_timestamp', table_name='auth_logs')
    op.drop_constraint('auth_logs_card_id_fkey', 'auth_logs', type_='foreignkey')
    op.create_foreign_key(None, 'auth_logs', 'demo_cards', ['card_id'], ['card_id'])
    op.alter_column('demo_cards', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'last_heartbeat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('100.0'))
    op.alter_column('sessions', 'last_score_update',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_sessions_card_id', table_name='sessions')
    op.drop_constraint('sessions_card_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'demo_cards', ['card_id'], ['card_id'])
    op.alter_column('site_risk_checks', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_site_risk_checks_checked_at', table_name='site_risk_checks')
    op.drop_index('idx_site_risk_checks_url', table_name='site_risk_checks')
    op.alter_column('trust_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_trust_events_session_id', table_name='trust_events')
    op.drop_index('idx_trust_events_timestamp', table_name='trust_events')
    op.drop_constraint('trust_events_session_id_fkey', 'trust_events', type_='foreignkey')
    op.create_foreign_key(None, 'trust_events', 'sessions', ['session_id'], ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trust_events', type_='foreignkey')
    op.create_foreign_key('trust_events_session_id_fkey', 'trust_events', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.create_index('idx_trust_events_timestamp', 'trust_events', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_trust_events_session_id', 'trust_events', ['session_id'], unique=False)
    op.alter_column('trust_events', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_site_risk_checks_url', 'site_risk_checks', ['url'], unique=False)
    op.create_index('idx_site_risk_checks_checked_at', 'site_risk_checks', [sa.text('checked_at DESC')], unique=False)
    op.alter_column('site_risk_checks', 'checked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_card_id_fkey', 'sessions', 'demo_cards', ['card_id'], ['card_id'], ondelete='CASCADE')
    op.create_index('idx_sessions_card_id', 'sessions', ['card_id'], unique=False)
    op.alter_column('sessions', 'last_score_update',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('100.0'))
    op.alter_column('sessions', 'last_heartbeat',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'issued_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('demo_cards', 'enrolled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'auth_logs', type_='foreignkey')
    op.create_foreign_key('auth_logs_card_id_fkey', 'auth_logs', 'demo_cards', ['card_id'], ['card_id'], ondelete='CASCADE')
    op.create_index('idx_auth_logs_timestamp', 'auth_logs', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_auth_logs_card_id', 'auth_logs', ['card_id'], unique=False)
    op.alter_column('auth_logs', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
